[package]
name = "simulacrum"
version = "0.1.0"
authors = ["Jason Grlicky <jason@paracosm.us>"]
description = "A small library for creating mock objects by hand using stable Rust."
keywords = ["mock", "mocking", "test", "testing", "unit-test", "TDD"]
categories = ["development-tools::testing"]
readme = "README.md"
documentation = "https://docs.rs/simulacrum"
repository = "https://github.com/pcsm/simulacrum/simulacrum"
license = "MIT"

[badges]
maintenance = { status = "actively-maintained" }

[dependencies]
debugit = "0.1"
handlebox = "0.3"