[package]
name = "simulacrum"
version = "0.1.0"
authors = ["Jason Grlicky <jason@paracosm.us>"]
description = "A small library for creating mock objects by hand in Stable Rust."
keywords = ["mock", "mocking", "test", "testing", "unit-test", "TDD"]
categories = ["development-tools::testing"]
license = "MIT"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
debugit = "0.1"
handlebox = { git = "ssh://bitbucket.org/paracosm/handlebox.git"}