[package]
name = "simulacrum_macros"
version = "0.1.0"
authors = ["Jason Grlicky <jason@paracosm.us>"]

[dependencies]
quote = "0.3"
syn = { version = "0.11.11", features = ["full"] }

[lib]
proc-macro = true